### PR TITLE
allow configuration with full url instead of protocol/baseUrl/port/prefix

### PR DESCRIPTION
**Pull request by tomaash**
This makes the configuration more flexible, and also allows to run the API against the same origin without the need to specify server address.

### CODE REVIEW

**Comment by tomaash** [comment]
@RobinBressan what do you think? I find this very useful.

**Comment by RobinBressan** [comment]
Hi,

This is indeed a use case, but you can also achieve it with `window.location.hostname` instead. IMO this solution is better because it avoids to add a new method on the restful object.

**Comment by tomaash** [comment]
Well, with support for different protocols and ports it looks like this:
```javascript
var hostname = window.location.hostname;
var protocol = window.location.protocol.replace(':','');
var port = window.location.port;
this.api = restful(hostname)
.prefixUrl('api')
.protocol(protocol);
.port(port);
```
is it really necessary when simple `/api` would suffice? Having same origin is still quite common, and it took me a while to figure out the above code correctly.

**Comment by jpetitcolas** [comment]
:+1: with @RobinBressan. Not sure we should add it as current library can already handle this use case.

**Pull request closed without merging**
