### PR TITLE
Fixed Firefox headers.forEach issue #66

### PR DESCRIPTION
**Pull request by jediger**
Added some array checking to make sure that a blank headers object doesn't break FF.

### CODE REVIEW

**Comment by jediger** [comment]
I fixed the bug that caused the CI to fail

**Comment by RobinBressan** [comment]
Hi,

Thanks for your contribution.

I do not understand your condition. Indeed the headers are not an array or a litteral object. It is a custom container from fetch (at least in the Github polyfill).

Furthermore, you don't need to commit es5 built files. We will push a dedicated commit on master after merge.

**Comment by jediger** [comment]
The issue we were having is that in the event that there are no response headers, Firefox says that forEach is not defined. So, I've changed the code to check for the length of response.headers to make sure that forEach will work. Issue #66 spells out the issue in more detail.

**Comment by yborunov** [comment]
I'm also facing this problem, but it's not the solution, unfortunately, since it's simply avoid using headers when forEach method unavailable. Headers still need to be accessed, but it's more like polyfilling problem which now works as all or nothing as oppose to check individual features available.

**Comment by cubbuk** [comment]
Hi I am getting the same error, when I added array checks as @jediger did I was able to run my project in firefox too, is it possible to make the necessary changes to published node module? Or is there any other workaround to fix this issue? Thanks

**Comment by RobinBressan** [comment]
@jediger Can you fix tests which are failling and remove the built files (minified and es5) from this PR? We'll do the merge after that.

**Comment by RobinBressan** [comment]
superseded by #70 but thank for pointing this issue!

**Pull request closed without merging**
