### PR TITLE
Add capable of specifying url suffix such as .json

### PR DESCRIPTION
**Pull request by danielking**
Some APIs return data in different format depending on the suffix of url.

### CODE REVIEW

**Comment by RobinBressan** [comment]
Hello,

I don't really see a use case for this PR as you can already do this by adding yourself `.json` to your endpoint's name when necessary. Furthermore, it might break the url when you chain several `one` for instance.

You can also use a request interceptor to add your prefix if you wish.

**Comment by danielking** [comment]
Thanks for your reply. I am trying to use Firebase as my data backend, it doesn't return json without url ending with .json. It might break something indeed, but my modifications are working here in my web app. Any other solution can do this?

**Comment by RobinBressan** [comment]
Have you tried to define a request interceptor which add `.json` to the url?

**Comment by danielking** [comment]
Wow! Sorry, I didn't notice that. Thanks!

**Pull request closed without merging**
